"""
This file has been translated from the old ::links
data that was present in ims_legacy.txt.
It should be easier to maintain as a python file.

The entries in the links_metadata array are triples comprised of
 "[tag]", "name", "url"

"""

links_metadata = [["[academy]", "Academe des sciences",
                   "http://en.wikipedia.org/wiki/French_Academy_of_Sciences"],
                  ["[academy]", "Academy of the Social Sciences in Australia",
                   "http://en.wikipedia.org/wiki/Academy_of_the_Social_Sciences_in_Australia"],
                  ["[academy]", "Académie des sciences",
                   "http://en.wikipedia.org/wiki/French_Academy_of_Sciences"],
                  ["[academy]", "Accademia Nazionale dei Lincei",
                   "http://en.wikipedia.org/wiki/Accademia_dei_Lincei"],
                  ["[academy]", "American Academy of Arts and Sciences",
                   "http://en.wikipedia.org/wiki/American_Academy_of_Arts_and_Sciences"],
                  ["[academy]", "Australian Academy of Science",
                   "http://en.wikipedia.org/wiki/Australian_Academy_of_Science"],
                  ["[academy]", "British Academy",
                   "http://en.wikipedia.org/wiki/British_Academy"],
                  ["[academy]", "Indian Academy of Sciences",
                   "http://en.wikipedia.org/wiki/Indian_Academy_of_Sciences"],
                  ["[academy]", "Indian National Science Academy",
                   "http://en.wikipedia.org/wiki/Indian_National_Science_Academy"],
                  ["[academy]", "Israel Academy of Sciences and Humanities",
                   "http://en.wikipedia.org/wiki/Israel_Academy_of_Sciences_and_Humanities"],
                  ["[academy]", "National Academy of Engineering",
                   "http://en.wikipedia.org/wiki/National_Academy_of_Engineering"],
                  ["[academy]", "National Academy of Sciences",
                   "http://en.wikipedia.org/wiki/National_Academy_of_Sciences"],
                  ["[academy]", "Norwegian Academy of Science and Letters",
                   "https://en.wikipedia.org/wiki/Norwegian_Academy_of_Science_and_Letters"],
                  ["[academy]", "Royal Danish Academy of Sciences and Letters",
                   "http://en.wikipedia.org/wiki/Royal_Danish_Academy_of_Sciences_and_Letters"],
                  ["[academy]", "Royal Spanish Academy of Sciences",
                   "http://en.wikipedia.org/wiki/Spanish_Royal_Academy_of_Sciences"],
                  ["[academy]", "The Royal Netherlands Academy of Arts and Sciences",
                   "http://en.wikipedia.org/wiki/Royal_Netherlands_Academy_of_Arts_and_Sciences"],
                  ["[academy]", "Third World Academy of Sciences",
                   "http://en.wikipedia.org/wiki/TWAS"],
                  ["[award]", "COPSS Presidents' Award",
                   "http://en.wikipedia.org/wiki/COPSS_Presidents%27_Award"],
                  ["[award]", "Copley Medal",
                   "http://en.wikipedia.org/wiki/Copley_Medal"],
                  ["[award]", "Elizabeth L. Scott Award",
                   "http://nisla05.niss.org/copss/PastAwardsScott.pdf"],
                  ["[award]", "F. N. David Award",
                   "http://nisla05.niss.org/copss/PastAwardsFNDavid.pdf"],
                  ["[award]", "George W. Snedecor Award",
                   "http://nisla05.niss.org/copss/PastAwardsSnedecor.pdf"],
                  ["[award]", "Guy Medal in Bronze",
                   "http://en.wikipedia.org/wiki/Guy_Medal#Bronze_Medallists"],
                  ["[award]", "Guy Medal in Gold",
                   "http://en.wikipedia.org/wiki/Guy_Medal#Gold_Medallists"],
                  ["[award]", "Guy Medal in Silver",
                   "http://en.wikipedia.org/wiki/Guy_Medal#Silver_Medallists"],
                  ["[award]", "Harry C. Carver Medal",
                   "http://imstat.org/awards/awards_IMS_recipients.htm"],
                  ["[award]", "IMS Lecture Awards",
                   "http://www.imstat.org/awards/lectures.htm"],
                  ["[award]", "Medal for Merit",
                   "http://en.wikipedia.org/wiki/Medal_for_Merit"],
                  ["[award]", "Medal of Freedom",
                   "http://en.wikipedia.org/wiki/Medal_of_Freedom"],
                  ["[award]", "National Medal of Science",
                   "http://en.wikipedia.org/wiki/National_Medal_of_Science"],
                  ["[award]", "Presidential Medal of Freedom",
                   "http://en.wikipedia.org/wiki/Presidential_Medal_of_Freedom"],
                  ["[award]", "R. A. Fisher Lecturer",
                   "http://nisla05.niss.org/copss/PastAwardsFisher.pdf"],
                  ["[award]", "Samuel S. Wilks Award",
                   "http://en.wikipedia.org/wiki/Wilks_Memorial_Award"],
                  ["[committee]", "Faculty Research Lecture Committee, University of California, Berkeley",
                   "http://academic-senate.berkeley.edu/committees/frl"],
                  ["[fellow]", "American Mathematical Society, Fellow",
                   "http://www.ams.org/profession/ams-fellows/ams-fellows"],
                  ["[fellow]", "IMS Fellow",
                   "http://www.imstat.org/awards/honored_fellows.htm"],
                  ["[fellow]", "MacArthur Fellow",
                   "http://en.wikipedia.org/wiki/MacArthur_Fellows_Program"],
                  ["[fellow]", "The Institute of Statistical Mathematics",
                   "http://www.ism.ac.jp/index_e.html"],
                  ["[fellow_ls]", "American Mathematical Society, Fellows List",
                   "http://www.ams.org/profession/fellows-list"],
                  ["[honor]", "Officer of the Order of Australia",
                   "http://en.wikipedia.org/wiki/Order_of_Australia"],
                  ["[honor]", "Officer of the Order of Canada",
                   "https://en.wikipedia.org/wiki/Order_of_Canada"],
                  ["[ims]", "IMS President",
                   "http://en.wikipedia.org/wiki/List_of_presidents_of_the_Institute_of_Mathematical_Statistics"],
                  ["[lecture]", "Faculty Research Lecturer, University of California, Berkeley",
                   "http://www.urel.berkeley.edu/faculty/history.html"],
                  ["[lecture]", "John von Neumann Lecturer",
                   "http://www.siam.org/prizes/sponsored/vonneumann.php"],
                  ["[lecture]", "Neyman Lecturer",
                   "http://imstat.org/awards/lectures_winners.htm"],
                  ["[lecture]", "Rietz Lecturer",
                   "http://www.imstat.org/awards/lectures_winners.htm#RietzLectures"],
                  ["[lecture]", "Wald Lecturer",
                   "http://www.imstat.org/awards/lectures_winners.htm"],
                  ["[president_list]", "President, Institute of Mathematical Statistics",
                   "http://imstat.org/officials/past_officials.html"],
                  ["[prize]", "Abel Prize",
                   "http://en.wikipedia.org/wiki/Abel_Prize"],
                  ["[prize]", "Birkhoff Prize",
                   "http://en.wikipedia.org/wiki/George_David_Birkhoff_Prize"],
                  ["[prize]", "Chauvenet Prize",
                   "http://en.wikipedia.org/wiki/Chauvenet_Prize"],
                  ["[prize]", "Doob Prize",
                   "http://www.ams.org/profession/prizes-awards/ams-prizes/doob-prize"],
                  ["[prize]", "Israel Prize",
                   "http://en.wikipedia.org/wiki/Israel_Prize"],
                  ["[prize]", "John von Neumann Theory Prize",
                   "http://en.wikipedia.org/wiki/John_von_Neumann_Theory_Prize"],
                  ["[prize]", "Kyoto Prize",
                   "http://en.wikipedia.org/wiki/Kyoto_Prize"],
                  ["[prize]", "Louve Prize",
                   "http://en.wikipedia.org/wiki/Lo%C3%A8ve_Prize"],
                  ["[prize]", "Nobel Prize in Economic Sciences",
                   "http://www.nobelprize.org/nobel_prizes/economics/laureates/"],
                  ["[prize]", "Norbert Wiener Prize in Applied Mathematics",
                   "http://en.wikipedia.org/wiki/Norbert_Wiener_Prize_in_Applied_Mathematics"],
                  ["[prize]", "Rollo Davidson Prize",
                   "http://en.wikipedia.org/wiki/Rollo_Davidson_Prize"],
                  ["[prize]", "Steele Prize",
                   "http://en.wikipedia.org/wiki/Leroy_P._Steele_Prize"],
                  ["[prize]", "The George B. Dantzig Prize",
                   "http://en.wikipedia.org/wiki/George_B._Dantzig_Prize#George_B._Dantzig_Prize"],
                  ["[prize]", "Wolf Prize in Physics",
                   "http://en.wikipedia.org/wiki/Wolf_Prize_in_Physics"],
                  ["[society]", "American Association for Advancement of Science",
                   "http://www.aaas.org/"],
                  ["[society]", "American Mathematical Society",
                   "http://www.ams.org/"],
                  ["[society]", "American Philosophical Society",
                   "http://en.wikipedia.org/wiki/American_Philosophical_Society"],
                  ["[society]", "Institute of Mathematical Statistics",
                   "http://imstat.org/"],
                  ["[society]", "Institute of Medicine",
                   "https://en.wikipedia.org/wiki/Institute_of_Medicine"],
                  ["[society]", "Royal Statistical Society",
                   "https://www.rss.org.uk/"],
                  ["[society]", "The Royal Society",
                   "http://en.wikipedia.org/wiki/Royal_Society"],
                  ["[society]", "The Royal Society of Canada",
                   "http://en.wikipedia.org/wiki/Royal_Society_of_Canada"],
                  ["[society]", "The Royal Society of Edinburgh",
                   "http://en.wikipedia.org/wiki/Royal_Society_of_Edinburgh"],
                  ["[society]", "The Royal Society of Literature",
                   "https://en.wikipedia.org/wiki/Royal_Society_of_Literature"],
                  ["[uk]", "Commander of the Order of the British Empire",
                   "http://en.wikipedia.org/wiki/Order_of_the_British_Empire"],
                  ["[uk]", "Knighted",
                   "http://en.wikipedia.org/wiki/Orders,_decorations,_and_medals_of_the_United_Kingdom"],
                  ["[usa]", "National Medal of Technology and Innovation",
                   "http://en.wikipedia.org/wiki/National_Medal_of_Technology_and_Innovation"],
              ]
